# Generated by Django 4.1.4 on 2022-12-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(default="backend creted user", max_length=20),
        ),
        migrations.AlterField(
            model_name="profile",
            name="post_code",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="street",
            field=models.CharField(default="backend creted user", max_length=20),
        ),
    ]
