# Generated by Django 4.1.4 on 2022-12-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofiles", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_pic",
            field=models.BinaryField(blank=True),
        ),
    ]
