# Generated by Django 4.2 on 2023-05-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofiles", "0004_profile_user_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=20)),
                ("random", models.CharField(max_length=50)),
            ],
        ),
    ]
