# Generated by Django 4.2 on 2023-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofiles", "0005_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="random",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="username",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
