# Generated by Django 4.1.4 on 2022-12-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("share", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="admin_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="open",
            field=models.BooleanField(default=False),
        ),
    ]
