# Generated by Django 4.1.4 on 2022-12-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0002_asset_approved_alter_assetgroup_admin_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetgroup",
            name="description",
            field=models.TextField(default="Description Text"),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="price_rental",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="price_time",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="assetgroup",
            name="price_usage",
            field=models.FloatField(default=0),
        ),
    ]
