# Generated by Django 4.1.4 on 2022-12-14 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("share", "0003_assetgroup_description_alter_assetgroup_open_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="price_rental",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="price_time",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="price_usage",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateTimeField()),
                ("date_to", models.DateTimeField()),
                ("billed", models.BooleanField(default=False)),
                ("paid", models.BooleanField(default=False)),
                ("beschwerde", models.TextField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="share.asset"
                    ),
                ),
            ],
        ),
    ]
