# Generated by Django 4.1.4 on 2022-12-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0005_transaction_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="beschwerde",
            field=models.TextField(blank=True, null=True),
        ),
    ]
