# Generated by Django 4.1.4 on 2022-12-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0006_alter_transaction_beschwerde"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="pic",
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name="assetgroup",
            name="pic",
            field=models.BinaryField(blank=True),
        ),
    ]
