# Generated by Django 4.1.4 on 2023-01-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0007_asset_pic_assetgroup_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="asset",
            name="form_data",
            field=models.TextField(default=""),
        ),
    ]
