# Generated by Django 4.1.4 on 2023-01-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0008_asset_description_alter_asset_form_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
