# Generated by Django 4.1.4 on 2023-01-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0009_transaction_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="share.assetgroup",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="share.asset",
            ),
        ),
    ]
