# Generated by Django 4.1.4 on 2023-01-21 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("share", "0013_alter_transaction_asset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="owner",
        ),
        migrations.AddField(
            model_name="transaction",
            name="requester",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
